# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: personal-ublue
# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/ublue-os/silverblue-main
# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: 38
# This description will be visible in the container metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
#  - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
# example:
# - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-37/atim-starship-fedora-37.repo

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  # needed for yafti (the first boot installer) (remove if you're not using yafti)
  - python3-pip
  - libadwaita # libadwaita comes with silverblue, but not with other flavors
  # add your own below
# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks: # maybe comments behind flatpaks cause issues, but unlikely
  - io.gitlab.librewolf-community # Hardend Firefox (UTC Timezone, english default, no DRM)
  - io.freetubeapp.FreeTube # Youtube without Ads, Subscribe without Account
  - org.kde.kdenlive # Video Editor
  - org.libreoffice.LibreOffice # Openoffice 
  - org.signal.Signal # Popular E2E Message Client
  - org.videolan.VLC # VLC Media Player
  - com.github.tchx84.Flatseal # Flatpak Permission Manager
  - com.obsproject.Studio # Streaming and Recording Application
  - com.jgraph.drawio.desktop # Visualize Charts like Networks, Controlflow of Code etc 
  - net.cozic.joplin_desktop # Markdown Editor
  - org.getmonero.Monero # Decentralized 
  - org.geogebra.GeoGebra # Math visualization
  - org.gimp.GIMP # FOSS Photoshop
  - com.github.flxzt.rnote # Great OneNote alternative 
  - chat.schildi.desktop # Matrix unoffical classic Messenger
  - im.riot.Riot # Matrix Offical Messenger
  - eu.betterbird.Betterbird # Email Client like Thunderbird
  - com.brave.Browser # Chromium Based Browser (DRM support)
  - org.kde.okular # PDF Viewer
  - org.qbittorrent.qBittorrent # Torrenting Client
  - com.mattjakeman.ExtensionManager
  - tv.kodi.Kodi # Modern Media Center 
  - org.keepassxc.KeePassXC # Encrypted local Password Manager
  - network.loki.Session # Session Decentralized E2E Messenger
  - com.vscodium.codium # Modern IDE - Visual Studio Code without Microsoft
  - io.github.aandrew_me.ytdn # Youtube Video Downloader
